version: '3'

services:
  python-container:
    image: "rashbirsingh/pythonimages:KTImage"
    container_name: KTImage
    ports: 
      - 5000:5000
    volumes:
      - ./vol:/var/pythoncode/vol
    environment:
      - PRINT=TEST
    build: .
